before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/vilsol/transcoder-go:{{ .Tag }}"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/vilsol/transcoder-go:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: 'dockerfiles/scratch.Dockerfile'

  - goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/vilsol/transcoder-go:{{ .Tag }}-nvidia"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}-nvidia"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}.{{ .Minor }}-nvidia"
      - "ghcr.io/vilsol/transcoder-go:latest-nvidia"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: 'dockerfiles/nvidia.Dockerfile'

  - goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/vilsol/transcoder-go:{{ .Tag }}-vaapi"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}-vaapi"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}.{{ .Minor }}-vaapi"
      - "ghcr.io/vilsol/transcoder-go:latest-vaapi"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: 'dockerfiles/vaapi.Dockerfile'

  - goarch: amd64
    use: buildx
    image_templates:
      - "ghcr.io/vilsol/transcoder-go:{{ .Tag }}-libvpl"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}-libvpl"
      - "ghcr.io/vilsol/transcoder-go:v{{ .Major }}.{{ .Minor }}-libvpl"
      - "ghcr.io/vilsol/transcoder-go:latest-libvpl"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: 'dockerfiles/libvpl.Dockerfile'
