name: build

on: [push, pull_request]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            file: transcoder-linux-amd64
            args: --best --lzma
            strip: true
            cgo: 0
          - os: windows-latest
            file: transcoder-win-amd64.exe
            args: -9
            strip: false
            cgo: 1
          - os: macos-latest
            file: transcoder-osx-amd64
            args: --best
            strip: false
            cgo: 1
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: go build -ldflags="-s -w" -v -o ${{ matrix.file }} .
        env:
          CGO_ENABLED: ${{ matrix.cgo }}
